relativeURLs = false
baseURL = "https://ptnews.store/"
languageCode = "en-us"
title = "PTNews Store â€“ Latest World News"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  title = "PTNews Store"
  description = "Latest world news from multiple trusted sources"

[outputFormats]
  sitemapindex = { mediaType = "application/xml", baseName = "sitemap", isHTML = false }
  postsitemap = { mediaType = "application/xml", baseName = "post-sitemap", isHTML = false }
  categoriessitemap = { mediaType = "application/xml", baseName = "categories-sitemap", isHTML = false }
  tagsitemap = { mediaType = "application/xml", baseName = "tag-sitemap", isHTML = false }

[outputs]
  home = ["HTML", "RSS", "JSON", "sitemapindex", "postsitemap", "categoriessitemap", "tagsitemap"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
uglyURLs = false

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact-us/"
    weight = 30

[[menu.main]]
    identifier = "privacy"
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 40
# Force GitHub Pages rebuild
